[book]
authors = ["Colin Walters"]
language = "en"
multilingual = false
src = "src"
title = "bootc"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
