name: Deploy docs to pages


on:
  pull_request:
    types: [ labeled ]
  push:
    branches: ["main"]


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    # should run on docs PRs and on pushes to main
    if: github.event.label.name == 'documentation' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.37
    steps:
      - uses: actions/checkout@v4
      - name: Install mdBook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Install mdbook-mermaid
        run: |
          tag=$(curl 'https://api.github.com/repos/badboy/mdbook-mermaid/releases/latest' | jq -r '.tag_name')
          url="https://github.com/badboy/mdbook-mermaid/releases/download/${tag}/mdbook-mermaid-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook-mermaid
          curl -sSL $url | tar -xz --directory=./mdbook-mermaid
          echo `pwd`/mdbook-mermaid >> $GITHUB_PATH
      - name: Install mdbook-linkcheck
        run: |
          tag=$(curl 'https://api.github.com/repos/Michael-F-Bryan/mdbook-linkcheck/releases/latest' | jq -r '.tag_name')
          archive="mdbook-linkcheck.x86_64-unknown-linux-gnu.zip"
          url="https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/${tag}/${archive}"
          mkdir mdbook-linkcheck
          curl -sSL -O $url && unzip ${archive} -d ./mdbook-linkcheck && chmod +x ./mdbook-linkcheck/mdbook-linkcheck
          echo `pwd`/mdbook-linkcheck >> $GITHUB_PATH
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with mdBook
        run: cd docs && mdbook-mermaid install && mdbook build

  deploy:
    if: github.event == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book
          retention-days: 7
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
