---
name: Integration Test

on:
  workflow_run:
    workflows: [Pull Request Info]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pr-info
      - name: Set env vars
        run: |
          echo "ALLOWED_USER=$(cat ./pr/allowed_user)" >> $GITHUB_ENV
          echo "SHA=$(cat ./pr/sha)" >> $GITHUB_ENV
          echo "REF=$(cat ./pr/ref)" >> $GITHUB_ENV
          echo "REPO_URL=$(cat ./pr/repo_url)" >> $GITHUB_ENV
  rhel94-integration:
    if: ${{ env.ALLOWED_USER == 'true' && !contains(github.event.pull_request.labels.*.name, 'control/skip-ci') }}
    continue-on-error: true
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        platform: [aws]
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}
          fetch-depth: 0

      - name: Run the tests
        uses: sclorg/testing-farm-as-github-action@v1
        with:
          compose: CentOS-Stream-9
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: ${{ env.REPO_RUL }}
          git_ref: ${{ env.REF }}
          arch: ${{ matrix.arch }}
          tmt_context: "arch=${{ matrix.arch }}"
          tmt_plan_regex: "${{ matrix.platform }}"
          tf_scope: private
          secrets: "QUAY_USERNAME=${{ secrets.QUAY_USERNAME }};QUAY_PASSWORD=${{ secrets.QUAY_PASSWORD }};QUAY_SECRET=${{ secrets.QUAY_SECRET }};RHEL_REGISTRY_URL=${{ secrets.RHEL_REGISTRY_URL }};DOWNLOAD_NODE=${{ secrets.DOWNLOAD_NODE }};AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }};AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          variables: "TEST_OS=rhel-9-4;PLATFORM=${{ matrix.platform }};ARCH=${{ matrix.arch }};AWS_REGION=${{ env.AWS_REGION }}"

  cs9-dev-integration:
    if: ${{ env.ALLOWED_USER == 'true' && !contains(github.event.pull_request.labels.*.name, 'control/skip-ci') }}
    continue-on-error: true
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        platform: [aws]
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}
          fetch-depth: 0

      - name: Run the tests
        uses: sclorg/testing-farm-as-github-action@v1
        with:
          compose: CentOS-Stream-9
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: ${{ env.REPO_URL }}
          git_ref: ${{ env.REF }}
          arch: ${{ matrix.arch }}
          tmt_context: "arch=${{ matrix.arch }}"
          tmt_plan_regex: "${{ matrix.platform }}"
          tf_scope: private
          secrets: "QUAY_USERNAME=${{ secrets.QUAY_USERNAME }};QUAY_PASSWORD=${{ secrets.QUAY_PASSWORD }};QUAY_SECRET=${{ secrets.QUAY_SECRET }};AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }};AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          variables: "TEST_OS=centos-stream-9;PLATFORM=${{ matrix.platform }};ARCH=${{ matrix.arch }};AWS_REGION=${{ env.AWS_REGION }}"
