# .github/workflows/update-generated.yml

name: 'Update Generated Files'

# This workflow is triggered on a schedule (every day at 3:15 AM UTC)
# and can also be triggered manually from the GitHub Actions UI.
on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * *'

jobs:
  update-and-pr:
    name: 'Update Generated Files and Create PR'
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel
    steps:
      # Step 1: Check out the repository's code
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Mark git directory as safe'
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        shell: bash

      # Step 2: Install the required dependencies by running the project's script
      - name: 'Install dependencies'
        run: ./ci/installdeps.sh
        shell: bash

      # --- Start Debugging Steps ---
      # These steps are added to diagnose why 'git rev-parse' might be failing.
      - name: 'Debug: List files in workspace'
        run: ls -laF
        shell: bash

      - name: 'Debug: Check git status'
        run: git status
        shell: bash

      - name: 'Debug: Run git rev-parse directly'
        run: git rev-parse HEAD
        shell: bash
      # --- End Debugging Steps ---

      # Step 3: Run the command to update the generated files
      - name: 'Update generated code'
        run: cargo xtask update-generated
        shell: bash

      # Step 4: Use a dedicated action to create a pull request if there are changes
      - name: 'Create Pull Request'
        uses: peter-evans/create-pull-request@v6
        with:
          # The token is required for the action to create a PR.
          # The GITHUB_TOKEN is automatically provided by GitHub Actions.
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update generated files'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          # A clear title for the pull request
          title: 'Automated: Update generated files'
          # A description for the pull request body
          body: |
            This PR was auto-generated by a GitHub Actions workflow.
            It contains updates to files generated by `cargo xtask update-generated`.
          # The branch name for the new pull request
          branch: 'actions/update-generated-files'
          # Labels to add to the pull request
          labels: 'automated, chore'

